// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp-DEH0MuxOEe7FD0vmDF510SPaA4UdqE',
    appId: '1:381190738082:web:d44eeb7537afbaa925c7fb',
    messagingSenderId: '381190738082',
    projectId: 'books-app-98299',
    authDomain: 'books-app-98299.firebaseapp.com',
    storageBucket: 'books-app-98299.appspot.com',
    measurementId: 'G-QGM0JGRLE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmbiEuS0H4LzmaKrA3GDDe4IcSpGx4-nE',
    appId: '1:381190738082:android:e6a5fc73e7cadae425c7fb',
    messagingSenderId: '381190738082',
    projectId: 'books-app-98299',
    storageBucket: 'books-app-98299.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1lbG0HEcbGhhyABBIwhy6oZJIrJrACsA',
    appId: '1:381190738082:ios:b9951723bd38f06b25c7fb',
    messagingSenderId: '381190738082',
    projectId: 'books-app-98299',
    storageBucket: 'books-app-98299.appspot.com',
    iosClientId: '381190738082-on7gq9ih8p72d8v0gdk72cc4q9s7qrmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );
}
